// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_followers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollower = `-- name: CreateFeedFollower :one
Insert Into feeds_followers(id,created_at,updated_at,user_id,feed_id)
Values ($1, $2, $3, $4, $5)
Returning id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedFollower(ctx context.Context, arg CreateFeedFollowerParams) (FeedsFollower, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollower,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedsFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
